name:                stop-tree
version:             0.1.0.0
github:              "no"
license:             BSD3
author:              "no"
maintainer:          "no"
copyright:           "no"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         STOP tree

dependencies:
- base >= 4.7 && < 5
- gloss

# library:
#   source-dirs: src

executables:
  stop-tree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
      #dependencies:
      #- stop-tree
